// <auto-generated />
using System;
using System.Collections.Generic;
using EFCoreCodeFirstSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCoreCodeFirstSample.Migrations.License
{
    [DbContext(typeof(LicenseContext))]
    [Migration("20231120120000_LicenseMigration")]
    partial class LicenseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCoreCodeFirstSample.Models.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, object>>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<bool>("InForce")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LicenseStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseType")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationFriendlyId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Licenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ac78372-86c8-4b1c-b90c-e490af783dc0"),
                            AccountId = "string",
                            AccountName = "string",
                            InForce = false,
                            OrganizationFriendlyId = "sep-11-2023-122b4029-6123-4e66-aaa1-2361d98c85be"
                        },
                        new
                        {
                            Id = new Guid("4c1586ea-5558-4917-b61d-abc80f7de3b3"),
                            AccountId = "sign-migration-nick-dev",
                            AccountName = "sign-migration-nick-dev",
                            Attributes = new Dictionary<string, object> { ["count"] = "23" },
                            InForce = false,
                            LicenseExpiryDate = new DateTime(2024, 9, 5, 17, 47, 0, 896, DateTimeKind.Utc),
                            LicenseName = "sign-migration-nick-dev",
                            LicenseStartDate = new DateTime(2023, 9, 4, 17, 47, 0, 896, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "sign-migration-nick-dev-36607087-77d5-46d2-9b98-3b58efb1d198"
                        },
                        new
                        {
                            Id = new Guid("c1fc1580-054e-448c-8747-cb64e396c9c6"),
                            AccountId = "string",
                            AccountName = "string",
                            Attributes = new Dictionary<string, object> { ["additionalProp1"] = "string", ["additionalProp2"] = "string", ["additionalProp3"] = "string" },
                            InForce = false,
                            LicenseExpiryDate = new DateTime(2024, 9, 8, 7, 56, 21, 140, DateTimeKind.Utc),
                            LicenseName = "string",
                            LicenseStartDate = new DateTime(2023, 9, 8, 7, 56, 21, 140, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "customer1testing1-432e6c06-41f6-4062-a0dd-f5002aab694d"
                        },
                        new
                        {
                            Id = new Guid("fc78abe4-b90a-4275-974c-0e53a73a3ef5"),
                            AccountId = "string",
                            AccountName = "string",
                            InForce = false,
                            OrganizationFriendlyId = "sep-5-2023-4708a347-d351-4833-8c47-2e3ac769f1a7"
                        },
                        new
                        {
                            Id = new Guid("8e8628e6-2cd2-4e6a-939e-869026aa19e8"),
                            AccountId = "string",
                            AccountName = "string",
                            InForce = false,
                            OrganizationFriendlyId = "test-blue-duck-july-123-604667c1-783e-46ae-9d47-eb3d8b98c9d5"
                        },
                        new
                        {
                            Id = new Guid("65328138-ad3f-4759-a955-6d33bb65a538"),
                            AccountId = "X0129232323",
                            AccountName = "GEHealthCare",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "10", ["NoOfTransaction"] = "200000" },
                            InForce = false,
                            LicenseExpiryDate = new DateTime(2024, 8, 18, 13, 36, 56, 922, DateTimeKind.Utc),
                            LicenseName = "Composer",
                            LicenseStartDate = new DateTime(2023, 8, 18, 13, 36, 56, 922, DateTimeKind.Utc),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "rlscst20231020-7939680c-92f9-4a0d-977b-3815dd876471"
                        },
                        new
                        {
                            Id = new Guid("4a3cd1e3-6fff-4a55-8319-d76781b053c7"),
                            AccountId = "X0129232323",
                            AccountName = "GEHealthCare",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100" },
                            InForce = false,
                            LicenseExpiryDate = new DateTime(2024, 8, 18, 13, 36, 56, 922, DateTimeKind.Utc),
                            LicenseName = "CPQ",
                            LicenseStartDate = new DateTime(2023, 8, 18, 13, 36, 56, 922, DateTimeKind.Utc),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "rlscst20231020-7939680c-92f9-4a0d-977b-3815dd876471"
                        },
                        new
                        {
                            Id = new Guid("3a77c79c-19c7-43a9-b7ad-939f1c57db62"),
                            AccountId = "string",
                            AccountName = "string",
                            InForce = false,
                            OrganizationFriendlyId = "sep-6-2023-int-test-a851d6a0-dcac-45a2-9bb7-01741a1c203a"
                        },
                        new
                        {
                            Id = new Guid("5abea323-ffc5-42be-a30d-ff1cc48c44ea"),
                            AccountId = "string",
                            AccountName = "string",
                            Attributes = new Dictionary<string, object> { ["additionalProp1"] = "string", ["additionalProp2"] = "string", ["additionalProp3"] = "string" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2023, 10, 10, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseName = "string",
                            LicenseStartDate = new DateTime(2023, 10, 9, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "approval-datasync112023-f9150169-c159-4ca7-bbf7-7dee67c0a218"
                        },
                        new
                        {
                            Id = new Guid("cb7a8d3a-a785-4410-b19e-305b52a38128"),
                            AccountId = "string",
                            AccountName = "string",
                            Attributes = new Dictionary<string, object> { ["additionalProp1"] = "string", ["additionalProp2"] = "string", ["additionalProp3"] = "string" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2023, 10, 10, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseName = "string",
                            LicenseStartDate = new DateTime(2023, 10, 9, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "approvaldevdatasync-048b0c17-3d00-4e5d-a63e-6a37d166dfe8"
                        },
                        new
                        {
                            Id = new Guid("9f14df49-233c-4ed6-9237-05de9a0f90d1"),
                            AccountId = "string",
                            AccountName = "string",
                            Attributes = new Dictionary<string, object> { ["additionalProp1"] = "string", ["additionalProp2"] = "string", ["additionalProp3"] = "string" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2023, 10, 10, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseName = "string",
                            LicenseStartDate = new DateTime(2023, 10, 9, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "approvaldevdatasync-048b0c17-3d00-4e5d-a63e-6a37d166dfe8"
                        },
                        new
                        {
                            Id = new Guid("5549a8db-1282-4a89-b14d-04aa59547154"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals-de-org-9a024855-9e56-4845-a273-40e6ae90346a"
                        },
                        new
                        {
                            Id = new Guid("23178382-fcba-48a8-bc3e-a25dde33ea71"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals-de-org-9a024855-9e56-4845-a273-40e6ae90346a"
                        },
                        new
                        {
                            Id = new Guid("4f0e8871-b2df-4112-81fc-e48214a239b2"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals-devs-sep-5836ef65-75fe-4cd2-9e32-145e86c4e667"
                        },
                        new
                        {
                            Id = new Guid("dfa9b3dc-5415-489b-9e08-c37ab3a2f7f0"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals-oct-12-2023-47d968a7-f082-4924-8015-563ad2350250"
                        },
                        new
                        {
                            Id = new Guid("9447d5ee-a4a0-45cb-91c3-888e4e14764f"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals-oct-test-13feefab-126f-461f-bea0-e64ea277e893"
                        },
                        new
                        {
                            Id = new Guid("f7594c3c-cd7e-4742-954f-7701516b21d3"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 1, 14, 54, 14, 751, DateTimeKind.Unspecified).AddTicks(1100),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 1, 14, 54, 14, 751, DateTimeKind.Unspecified).AddTicks(1000),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals-test-1102-1-036fcbba-20b7-4920-bdab-7bb95bdb586f"
                        },
                        new
                        {
                            Id = new Guid("3faa6da8-5522-4503-bc55-2b53873ead11"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals091423-be8b8668-5b85-4c34-90a8-d2580c5a8b84"
                        },
                        new
                        {
                            Id = new Guid("b1935426-3965-4112-aedc-8d285a6b3d1c"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals091523-3f1c4539-2ad1-40c0-8981-e6c43c10eb18"
                        },
                        new
                        {
                            Id = new Guid("79181611-15b8-44c4-9c8b-616316c509c0"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals092023-9a199ddb-de2c-4bb5-9d15-9dfc604d1bd0"
                        },
                        new
                        {
                            Id = new Guid("a8911aa4-7cc2-4311-89db-9f8912aee4c9"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals092123-4cb24515-1026-4b66-ad32-1f125eb1bbc4"
                        },
                        new
                        {
                            Id = new Guid("e1736d01-fef4-4ef3-80ff-3fe7ea3bdc74"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals092523-25f601b1-cf56-4aa0-8b45-9a98bf8689f4"
                        },
                        new
                        {
                            Id = new Guid("f98f7382-9561-4559-8dd4-b7224ac75a0f"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals092623-3d670757-087a-4b49-a565-1d43c9b5c1c4"
                        },
                        new
                        {
                            Id = new Guid("8131630d-2fad-4781-a982-f39afb0cc963"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals100323-b7d414bd-32f4-40e9-86e2-cef1497882c4"
                        },
                        new
                        {
                            Id = new Guid("19f94209-a283-435c-93b4-1e6f256c2549"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals100523-0e665868-1d45-49b6-bc01-e877104ed2a2"
                        },
                        new
                        {
                            Id = new Guid("fa84434c-53e1-49c7-b41f-13c58f704e49"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals101223-7fcf1e1a-0d97-436b-95af-cd6c2a132415"
                        },
                        new
                        {
                            Id = new Guid("e3b4fe63-ce71-4e5b-8f9b-25fbcfef5e27"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals101323-ebe16796-7077-4a8e-ac14-f1b86feb4b72"
                        },
                        new
                        {
                            Id = new Guid("5d1d784c-5856-4561-9447-1f277c5028c1"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals101423-f1094b93-2481-4b77-baf5-7a3ad0880458"
                        },
                        new
                        {
                            Id = new Guid("715a41f6-6562-4f37-93e8-5667dc1a7629"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals101623-ceee1089-b521-417d-abc9-1eec6dd5b8de"
                        },
                        new
                        {
                            Id = new Guid("8db6f5c5-7076-41f8-87f0-e613278e29ad"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals102423-8792bcfa-1ac6-4519-8203-0881424becfb"
                        },
                        new
                        {
                            Id = new Guid("1280ea6e-6f9a-418b-9265-5ab3af58ef09"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals102423-test-2-ce211db6-925b-4542-ae70-b2f382423e7d"
                        },
                        new
                        {
                            Id = new Guid("4bdba2fe-4ee9-4458-8b67-08f43cc685bf"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            InForce = false,
                            OrganizationFriendlyId = "approvals102423-test-41c45d81-1256-47a9-a145-5700098833d7"
                        },
                        new
                        {
                            Id = new Guid("909a9ceb-b298-469a-9e56-dcd14537ed5f"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 10, 24, 18, 50, 21, 912, DateTimeKind.Unspecified).AddTicks(2810),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 10, 24, 18, 50, 21, 912, DateTimeKind.Unspecified).AddTicks(2680),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals102523-656ae20b-33a5-4e84-b123-98b556e73134"
                        },
                        new
                        {
                            Id = new Guid("8512d6df-9197-4e6d-ba98-40b533bc5178"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 10, 25, 19, 50, 33, 881, DateTimeKind.Unspecified).AddTicks(4180),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 10, 25, 19, 50, 33, 881, DateTimeKind.Unspecified).AddTicks(4070),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals102623-207b271d-3441-4ae8-95a1-1d857c31aca1"
                        },
                        new
                        {
                            Id = new Guid("52ee06ea-83ff-4af6-97a1-0f25f7d439cc"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 10, 26, 16, 7, 21, 764, DateTimeKind.Unspecified).AddTicks(5490),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 10, 26, 16, 7, 21, 764, DateTimeKind.Unspecified).AddTicks(5360),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals10272023-a652c6b2-78eb-411c-afb4-d06d8b5ee6c2"
                        },
                        new
                        {
                            Id = new Guid("b9854942-f83a-4cff-b432-f3c707b5bf13"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 10, 26, 15, 38, 44, 78, DateTimeKind.Unspecified).AddTicks(2580),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 10, 26, 15, 38, 44, 78, DateTimeKind.Unspecified).AddTicks(2470),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals102723-7c8630b5-b648-4c7a-92a9-ef5525c9276a"
                        },
                        new
                        {
                            Id = new Guid("e16193a5-db1b-495c-9cc3-02ea0df12a6d"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 1, 17, 16, 58, 289, DateTimeKind.Unspecified).AddTicks(1370),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 1, 17, 16, 58, 289, DateTimeKind.Unspecified).AddTicks(1240),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11022023-1c73ca3a-041d-4952-9cc1-f6861c01d6c8"
                        },
                        new
                        {
                            Id = new Guid("c768f394-695c-4460-8153-1cec8886579e"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 1, 14, 58, 57, 519, DateTimeKind.Unspecified).AddTicks(5420),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 1, 14, 58, 57, 519, DateTimeKind.Unspecified).AddTicks(5310),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals110323-2712c75a-0204-4869-a245-243508d7163b"
                        },
                        new
                        {
                            Id = new Guid("0a18a78d-5afb-4108-9cbf-bc4f43cefdf6"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 7, 2, 13, 11, 422, DateTimeKind.Unspecified).AddTicks(6060),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 7, 2, 13, 11, 422, DateTimeKind.Unspecified).AddTicks(5940),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11072023-87e23212-a05e-4bc6-b65c-f9ac773612ac"
                        },
                        new
                        {
                            Id = new Guid("dae1c0dd-1e7a-42c9-80bd-4baade34fb8c"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 7, 2, 19, 39, 579, DateTimeKind.Unspecified).AddTicks(9020),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 7, 2, 19, 39, 579, DateTimeKind.Unspecified).AddTicks(8880),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11082023-2786e1fe-b940-43be-84d6-af8ee0fc7318"
                        },
                        new
                        {
                            Id = new Guid("a59421c6-18b9-4230-809e-21291790139c"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 7, 14, 51, 36, 361, DateTimeKind.Unspecified).AddTicks(590),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 7, 14, 51, 36, 361, DateTimeKind.Unspecified).AddTicks(510),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11092023-2f8629a1-7773-4580-bdb3-838d00e8e497"
                        },
                        new
                        {
                            Id = new Guid("f7e50684-3db7-46ef-9de5-067f03444aaa"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 9, 0, 25, 49, 551, DateTimeKind.Unspecified).AddTicks(8670),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 9, 0, 25, 49, 551, DateTimeKind.Unspecified).AddTicks(8570),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11102023-e3afbd68-8caa-4853-be2f-5f475d195a0b"
                        },
                        new
                        {
                            Id = new Guid("cb069ebc-4c64-4d2b-9121-379895831278"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 15, 21, 19, 47, 740, DateTimeKind.Unspecified).AddTicks(7130),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 15, 21, 19, 47, 740, DateTimeKind.Unspecified).AddTicks(7000),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11162023-65e73486-23a1-4f53-8b26-6122769830e6"
                        },
                        new
                        {
                            Id = new Guid("e21e72d3-35ef-46b5-926d-38b82b42f535"),
                            AccountId = "022784664444",
                            AccountName = "AWS",
                            Attributes = new Dictionary<string, object> { ["NoOfUser"] = "100", ["NoOfTransaction"] = "200000000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 11, 16, 18, 7, 28, 421, DateTimeKind.Unspecified).AddTicks(6170),
                            LicenseName = "triallicenseworkflow",
                            LicenseStartDate = new DateTime(2023, 11, 16, 18, 7, 28, 421, DateTimeKind.Unspecified).AddTicks(6090),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "approvals11172023-ff6c0285-ef06-47b6-b90c-cfbd7fa9f112"
                        },
                        new
                        {
                            Id = new Guid("1941cc2f-3aee-4997-b2e6-68c89aec9340"),
                            AccountId = "001DM00002DoL24YAF",
                            AccountName = "Test Conga SIgn Acc",
                            Attributes = new Dictionary<string, object> { ["Seats"] = "50", ["TransactionLimit"] = "5000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseName = "Conga Composer",
                            LicenseStartDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseType = "Paid",
                            OrganizationFriendlyId = "auedm0000008peo4a2-eca2ff79-ba91-4977-a195-5b3b8f675fb9"
                        },
                        new
                        {
                            Id = new Guid("4ae17e83-e69a-4d52-933a-606ef8527d04"),
                            AccountId = "001DM00002DoL24YAF",
                            AccountName = "Test Conga SIgn Acc",
                            Attributes = new Dictionary<string, object> { ["Seats"] = "-1", ["TransactionLimit"] = "30" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseName = "Conga Sign",
                            LicenseStartDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "auedm0000008peo4a2-eca2ff79-ba91-4977-a195-5b3b8f675fb9"
                        },
                        new
                        {
                            Id = new Guid("acfb9750-40b1-4829-977a-4c669a7574bd"),
                            AccountId = "001DM00002DoL24YAF",
                            AccountName = "Test Conga SIgn Acc",
                            Attributes = new Dictionary<string, object> { ["Seats"] = "51", ["TransactionLimit"] = "5000" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseName = "Conga Composer",
                            LicenseStartDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseType = "Paid",
                            OrganizationFriendlyId = "auedm0000008pfg4am-3be6f24d-bea5-4e2f-9435-4651a4358e5e"
                        },
                        new
                        {
                            Id = new Guid("c44d166b-deda-48cc-9887-36038afdcf2d"),
                            AccountId = "001DM00002DoL24YAF",
                            AccountName = "Test Conga SIgn Acc",
                            Attributes = new Dictionary<string, object> { ["Seats"] = "-1", ["TransactionLimit"] = "30" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseName = "Conga Sign",
                            LicenseStartDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseType = "Trial",
                            OrganizationFriendlyId = "auedm0000008ply4am-5345e2ae-27c9-42a6-8630-d69d08167396"
                        },
                        new
                        {
                            Id = new Guid("f3266a0c-5796-4d39-8c30-e9abcb39be0d"),
                            AccountId = "string",
                            AccountName = "string",
                            Attributes = new Dictionary<string, object> { ["additionalProp1"] = "string", ["additionalProp2"] = "string", ["additionalProp3"] = "string" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2023, 10, 10, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseName = "license1",
                            LicenseStartDate = new DateTime(2023, 10, 9, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "approvaldevdatasync-048b0c17-3d00-4e5d-a63e-6a37d166dfe8"
                        },
                        new
                        {
                            Id = new Guid("82c325ac-8a35-433e-bbaf-e16c8c4d7576"),
                            AccountId = "string",
                            AccountName = "string",
                            Attributes = new Dictionary<string, object> { ["additionalProp1"] = "string", ["additionalProp2"] = "string", ["additionalProp3"] = "string" },
                            InForce = true,
                            LicenseExpiryDate = new DateTime(2022, 10, 10, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseName = "license2",
                            LicenseStartDate = new DateTime(2022, 10, 9, 12, 35, 18, 676, DateTimeKind.Utc),
                            LicenseType = "trial",
                            OrganizationFriendlyId = "approvaldevdatasync-048b0c17-3d00-4e5d-a63e-6a37d166dfe8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
